In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import pyodbc
from sqlalchemy import create_engine

In [3]:
conn = pyodbc.connect(
    "Driver={SQL Server};"
    "Server=ASMAA;"  
    "Database=project;"        
    "Trusted_Connection=yes;"
)

In [4]:
FactWeatherObservation = pd.read_sql("SELECT * FROM FactWeatherObservation", conn)
print(FactWeatherObservation.head())

   observation_id  time_id  location_id  event_id  temperature  humidity  \
0               1        1            1       800        23.42      56.0
1               2        2            2       800        19.98      73.0
2               3        3            3       800        26.01      56.0
3               4        4            4       800        24.55      60.0
4               5        5            5       803        12.37      70.0

   wind_speed  wind_direction  pressure  precipitation  visibility  \
0        5.14            10.0    1017.0            0.0     10000.0
1        2.57           100.0    1017.0            0.0     10000.0
2        5.14           180.0    1024.0            0.0     10000.0
3        5.14           240.0    1007.0            0.0     10000.0
4        4.63           260.0    1023.0            0.0     10000.0

   cloud_coverage  model_id
0             0.0         1
1             0.0         1
2             0.0         1
3             0.0         1
4            75.0         1

C:\Users\asmaa\AppData\Local\Temp\ipykernel_10004\1144276950.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  FactWeatherObservation = pd.read_sql("SELECT * FROM FactWeatherObservation", conn)

In [5]:
t2 = pd.read_sql("SELECT * FROM DimWeatherEvent", conn)
print(t2.head())

   event_id Weather_condition                        description severity
0        94          Overcast   Cloudy skies throughout the day.   Normal
1       111  Partially cloudy  Partly cloudy throughout the day.   Normal
2       200      Thunderstorm       thunderstorm with light rain    Light
3       300           Drizzle            light intensity drizzle    Light
4       331          Overcast   Cloudy skies throughout the day.   Normal

C:\Users\asmaa\AppData\Local\Temp\ipykernel_10004\4184429833.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  t2 = pd.read_sql("SELECT * FROM DimWeatherEvent", conn)

In [6]:
FactWeatherObservation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4391 entries, 0 to 4390
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   observation_id  4391 non-null   int64
 1   time_id         4391 non-null   int64
 2   location_id     4391 non-null   int64
 3   event_id        4391 non-null   int64
 4   temperature     4391 non-null   float64
 5   humidity        4391 non-null   float64
 6   wind_speed      4391 non-null   float64
 7   wind_direction  4391 non-null   float64
 8   pressure        4391 non-null   float64
 9   precipitation   4391 non-null   float64
 10  visibility      4391 non-null   float64
 11  cloud_coverage  4391 non-null   float64
 12  model_id        4391 non-null   int64
dtypes: float64(8), int64(5)
memory usage: 446.1 KB

In [7]:
FactWeatherObservation[['temperature','humidity','wind_speed','wind_direction','pressure','precipitation','visibility','cloud_coverage']].describe().round(2)

,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage
count,4391.00,4391.00,4391.00,4391.00,4391.00,4391.00,4391.00,4391.00
mean,17.96,73.36,9.02,157.72,1018.06,0.16,6024.87,46.96
std,5.64,13.65,8.70,129.38,6.36,1.67,4733.98,38.81
min,3.41,30.00,0.00,0.00,1006.00,0.00,5.00,0.00
25%,13.56,63.00,2.57,40.00,1013.00,0.00,22.70,1.00
50%,18.20,76.20,6.00,126.00,1018.00,0.00,10000.00,40.00
75%,22.42,84.00,13.00,300.00,1022.50,0.00,10000.00,84.00
max,32.00,100.00,49.40,360.00,1032.00,25.34,10000.00,100.00

In [8]:
FactWeatherObservation.isna().sum()

observation_id    0
time_id           0
location_id       0
event_id          0
temperature       0
humidity          0
wind_speed        0
wind_direction    0
pressure          0
precipitation     0
visibility        0
cloud_coverage    0
model_id          0
dtype: int64

In [9]:
FactWeatherObservation.duplicated().sum()

np.int64(0)

In [10]:
FactWeatherObservation[FactWeatherObservation['precipitation'] == 0.0].shape[0]

4276

In [11]:
len(FactWeatherObservation['precipitation'].value_counts())

19

In [12]:
FactWeatherObservation['precipitation'].value_counts()

precipitation
0.00     4276
0.10       24
0.20       19
10.40      17
5.30       16
24.34      15
0.11        4
0.39        4
2.37        3
0.27        2
0.18        2
0.19        2
0.49        1
0.13        1
1.54        1
24.23       1
1.00        1
25.34       1
0.60        1
Name: count, dtype: int64

In [13]:
FactWeatherObservation['precipitation'].unique()

array([ 0.  ,  0.18,  0.49,  0.39,  1.54,  0.2 ,  2.37,  0.27,  0.1 ,
        0.11,  0.13, 24.23,  1.  ,  5.3 , 10.4 , 24.34,  0.19, 25.34,
        0.6 ])

In [14]:
FactWeatherObservation['precipitation'].duplicated().sum()

np.int64(4372)

In [15]:
FactWeatherObservation['model_id'].value_counts()

model_id
1    2826
2    1565
Name: count, dtype: int64

In [16]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id
1416,1429,1116,8,800,7.28,91.0,1.42,95.0,1025.0,0.0,10000.0,0.0,1
2331,2344,688,4,3743,14.40,88.6,30.00,158.5,1011.2,0.0,11.4,84.3,2
739,752,761,4,803,20.58,59.0,6.17,150.0,1008.0,0.0,10000.0,75.0,1
2309,2322,1282,13,3743,19.40,72.1,22.30,38.4,1021.5,0.0,19.6,77.3,2
2227,2240,1282,12,347,27.40,34.4,8.30,143.2,1010.8,0.0,21.5,0.0,2
2403,2416,688,3,7608,14.00,79.8,28.60,11.1,1016.5,0.0,14.7,94.5,2
3286,3299,1195,5,804,13.73,84.0,4.12,70.0,1029.0,0.0,10000.0,100.0,1
64,65,65,5,803,14.93,81.0,3.09,240.0,1024.0,0.0,10000.0,82.0,1
3677,3690,688,1,6886,22.80,57.9,16.60,2.2,1016.5,0.0,22.9,18.6,2
525,526,532,12,701,21.05,100.0,1.03,0.0,1012.0,0.0,2800.0,20.0,1

In [17]:
def temp_cat(temp):
    if temp < 10:
        return 'Cold'
    elif temp < 20:
        return 'Mild'
    elif temp < 30:
        return 'Warm'
    else:
        return 'Hot'

FactWeatherObservation['Temp_category'] = FactWeatherObservation['temperature'].apply(temp_cat)

In [18]:
FactWeatherObservation['Temp_category'].value_counts()

Temp_category
Mild    2300
Warm    1747
Cold     338
Hot        6
Name: count, dtype: int64

In [19]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id,Temp_category
3827,3840,688,16,3743,25.10,76.6,30.60,215.3,1013.0,0.0,12.1,79.1,2,Warm
3634,3647,1238,19,800,19.92,55.0,5.14,350.0,1019.0,0.0,10000.0,0.0,1,Mild
3170,3183,1138,10,803,15.81,85.0,1.72,47.0,1019.0,0.0,10000.0,83.0,1,Mild
4328,4341,1446,9,804,12.79,82.0,4.12,50.0,1026.0,0.0,10000.0,100.0,1,Mild
2725,2738,688,4,5568,14.40,88.3,30.00,156.3,1011.1,0.0,11.4,84.1,2,Mild
3214,3227,1157,12,721,22.05,73.0,0.00,0.0,1010.0,0.0,3500.0,0.0,1,Warm
2106,2119,1271,11,721,26.99,61.0,2.57,100.0,1008.0,0.0,4000.0,0.0,1,Warm
3292,3305,1198,8,800,5.30,92.0,1.52,126.0,1025.0,0.0,10000.0,0.0,1,Cold
2367,2380,1282,2,6131,22.90,62.0,15.50,347.7,1016.8,0.0,23.5,48.9,2,Warm
1327,1340,1083,19,800,15.14,74.0,5.14,350.0,1020.0,0.0,10000.0,7.0,1,Mild

In [20]:
FactWeatherObservation['cloud_coverage'].max()

np.float64(100.0)

In [21]:
def cloud_level(value):
    if value <= 25:
        return 'Clear'
    elif value <= 50:
        return 'Partly Cloudy'
    elif value <= 75:
        return 'Cloudy'
    else:
        return 'Overcast'

FactWeatherObservation['Cloud_level'] = FactWeatherObservation['cloud_coverage'].apply(cloud_level)

In [22]:
FactWeatherObservation['Cloud_level'].value_counts()

Cloud_level
Clear            1744
Overcast         1324
Cloudy            701
Partly Cloudy     622
Name: count, dtype: int64

In [23]:
def visibility_level(v):
    if v <= 1000:
        return 'Very Low'
    elif v <= 5000:
        return 'Low'
    elif v <= 9000:
        return 'Moderate'
    else:
        return 'High'

FactWeatherObservation['Visibility_level'] = FactWeatherObservation['visibility'].apply(visibility_level)

In [24]:
FactWeatherObservation['Visibility_level'].value_counts()

Visibility_level
High        2529
Very Low    1565
Low          275
Moderate      22
Name: count, dtype: int64

In [25]:
FactWeatherObservation['visibility'].max()

np.float64(10000.0)

In [26]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id,Temp_category,Cloud_level,Visibility_level
3275,3288,673,3,7798,14.10,88.1,37.90,40.9,1013.4,0.0,6.3,98.3,2,Mild,Overcast,Very Low
2498,2511,1411,10,802,12.75,81.0,0.92,326.0,1019.0,0.0,10000.0,37.0,1,Mild,Partly Cloudy,High
3966,3979,1346,5,804,11.56,81.0,2.06,350.0,1030.0,0.0,10000.0,100.0,1,Mild,Overcast,High
1823,1836,688,21,455,19.30,76.2,11.20,53.1,1018.6,0.0,24.1,63.3,2,Mild,Cloudy,Very Low
2178,2191,1289,7,804,9.57,91.0,1.29,35.0,1024.0,0.0,10000.0,92.0,1,Cold,Overcast,High
2609,2622,1282,6,111,11.10,80.1,6.00,53.8,1031.1,0.0,23.5,69.1,2,Mild,Cloudy,Very Low
1232,1245,981,4,804,20.99,57.0,6.17,150.0,1008.0,0.0,10000.0,100.0,1,Warm,Overcast,High
1017,1030,941,4,804,20.96,57.0,6.17,150.0,1008.0,0.0,10000.0,100.0,1,Warm,Overcast,High
2318,2331,1340,17,801,17.73,71.0,6.26,300.0,1021.0,0.0,10000.0,20.0,1,Mild,Clear,High
247,248,248,7,804,12.75,92.0,3.13,287.0,1020.0,0.0,10000.0,100.0,1,Mild,Overcast,High

In [27]:
def wind_category(speed):
    if speed <= 2.5:
        return 'Calm'
    elif speed <= 5.0:
        return 'Light Breeze'
    elif speed <= 10.0:
        return 'Moderate'
    elif speed <= 20.0:
        return 'Strong'
    else:
        return 'Stormy'

FactWeatherObservation['Wind_category'] = FactWeatherObservation['wind_speed'].apply(wind_category)

In [28]:
FactWeatherObservation['Wind_category'].value_counts()

Wind_category
Moderate        1167
Calm            1015
Light Breeze     836
Strong           782
Stormy           591
Name: count, dtype: int64

In [29]:
FactWeatherObservation['wind_speed'].max()

np.float64(49.4)

In [30]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id,Temp_category,Cloud_level,Visibility_level,Wind_category
1068,1081,1021,15,802,21.88,81.0,7.20,320.0,1011.0,0.00,10000.0,40.0,1,Warm,Partly Cloudy,High,Moderate
2606,2619,1441,4,801,16.26,76.0,5.14,160.0,1013.0,0.00,10000.0,20.0,1,Mild,Clear,High,Moderate
27,28,28,8,500,7.76,90.0,1.79,263.0,1021.0,0.18,10000.0,85.0,1,Cold,Overcast,High,Calm
3408,3421,1196,6,804,13.20,85.0,1.03,0.0,1031.0,0.00,10000.0,100.0,1,Mild,Overcast,High,Calm
473,474,480,6,804,11.15,85.0,1.54,170.0,1025.0,0.00,10000.0,100.0,1,Mild,Overcast,High,Calm
1414,1427,1114,6,804,13.00,89.0,0.51,0.0,1030.0,0.00,10000.0,100.0,1,Mild,Overcast,High,Calm
1209,1222,999,3,804,14.21,91.0,10.80,50.0,1012.0,0.00,10000.0,100.0,1,Mild,Overcast,High,Strong
1093,1106,1036,20,800,27.71,59.0,6.17,50.0,1012.0,0.00,10000.0,0.0,1,Warm,Clear,High,Moderate
210,211,211,10,800,12.75,85.0,1.99,284.0,1018.0,0.00,10000.0,5.0,1,Mild,Clear,High,Calm
3996,4009,1343,20,801,25.74,71.0,6.17,20.0,1014.0,0.00,10000.0,20.0,1,Warm,Clear,High,Moderate

In [32]:
FactWeatherObservation['Comfort_index'] = (
    FactWeatherObservation['temperature'] - (0.55 - 0.0055 * FactWeatherObservation['humidity']) * (FactWeatherObservation['temperature'] - 14.5)
).round(2)

In [33]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id,Temp_category,Cloud_level,Visibility_level,Wind_category,Comfort_index
3555,3568,688,20,455,12.80,61.7,28.00,292.8,1017.9,0.0,17.6,41.5,2,Mild,Partly Cloudy,Very Low,Stormy,13.16
861,874,883,5,804,15.01,81.0,2.57,50.0,1029.0,0.0,10000.0,100.0,1,Mild,Overcast,High,Light Breeze,14.96
2689,2702,1282,6,111,11.10,80.1,6.00,53.8,1031.1,0.0,23.5,69.1,2,Mild,Cloudy,Very Low,Moderate,11.47
2889,2902,1050,9,800,14.57,85.0,4.63,40.0,1025.0,0.0,10000.0,0.0,1,Mild,Clear,High,Light Breeze,14.56
2697,2710,1282,21,111,18.40,76.2,13.20,348.6,1018.3,0.0,22.9,36.7,2,Mild,Partly Cloudy,Very Low,Strong,17.89
4221,4234,688,16,2989,25.20,76.5,30.60,211.7,1012.9,0.0,11.5,80.0,2,Warm,Overcast,Very Low,Stormy,23.82
3545,3558,673,22,4590,21.50,73.1,27.00,319.6,1012.9,0.0,11.8,67.2,2,Warm,Cloudy,Very Low,Stormy,20.46
2623,2636,1282,13,5568,19.40,72.8,22.30,38.0,1021.5,0.0,19.1,77.2,2,Mild,Overcast,Very Low,Stormy,18.67
2562,2575,1414,2,800,21.80,59.0,3.19,3.0,1017.0,0.0,10000.0,0.0,1,Warm,Clear,High,Light Breeze,20.15
1054,1067,935,1,800,23.42,49.0,5.14,20.0,1016.0,0.0,10000.0,0.0,1,Warm,Clear,High,Moderate,20.92

In [34]:
def comfort_label(value):
    if value < 15:
        return "Very Cold"
    elif 15 <= value <= 22:
        return "Comfortable"
    elif 23 <= value <= 28:
        return "Warm"
    elif 29 <= value <= 35:
        return "Hot"
    else:
        return "Very Hot"

FactWeatherObservation['Comfort_level'] = FactWeatherObservation['Comfort_index'].apply(comfort_label)

In [35]:
FactWeatherObservation.sample(10)

,observation_id,time_id,location_id,event_id,temperature,humidity,wind_speed,wind_direction,pressure,precipitation,visibility,cloud_coverage,model_id,Temp_category,Cloud_level,Visibility_level,Wind_category,Comfort_index,Comfort_level
1979,1992,688,8,455,9.00,86.4,6.10,69.8,1024.3,0.0,22.4,70.2,2,Cold,Cloudy,Very Low,Moderate,9.41,Very Cold
346,347,347,6,801,10.47,84.0,1.54,220.0,1025.0,0.0,10000.0,20.0,1,Mild,Clear,High,Calm,10.82,Very Cold
997,1010,941,4,804,20.96,57.0,6.17,150.0,1008.0,0.0,10000.0,100.0,1,Warm,Overcast,High,Moderate,19.43,Comfortable
259,260,260,19,800,22.12,59.0,5.14,350.0,1010.0,0.0,10000.0,0.0,1,Warm,Clear,High,Moderate,20.40,Comfortable
279,280,280,19,800,22.12,59.0,5.14,350.0,1010.0,0.0,10000.0,0.0,1,Warm,Clear,High,Moderate,20.40,Comfortable
2517,2530,1282,20,9455,14.60,64.3,15.60,263.5,1020.0,0.0,17.6,5.6,2,Mild,Clear,Very Low,Strong,14.58,Very Cold
324,325,325,4,800,23.03,65.0,5.14,260.0,1012.0,0.0,10000.0,0.0,1,Warm,Clear,High,Moderate,21.39,Comfortable
194,195,195,14,803,22.93,64.0,6.69,330.0,1012.0,0.0,10000.0,75.0,1,Warm,Cloudy,High,Moderate,21.26,Comfortable
849,862,871,14,800,18.93,88.0,3.09,320.0,1015.0,0.0,10000.0,0.0,1,Mild,Clear,High,Light Breeze,18.64,Comfortable
2304,2317,1333,10,802,14.73,85.0,1.50,311.0,1019.0,0.0,10000.0,44.0,1,Mild,Partly Cloudy,High,Calm,14.71,Very Cold

In [36]:
engine = create_engine(
    "mssql+pyodbc://@ASMAA/project?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [38]:
FactWeatherObservation.to_sql('FactWeatherObservation', con=engine, if_exists='replace', index=False)

101